from app.database import SessionLocal
from app.models import Resource

# ── NeetCode channel / playlists (fallback when no direct video link) ─────────
_NC = "https://www.youtube.com/@NeetCode"
_NC_150 = "https://www.youtube.com/playlist?list=PLot-Xpze53ldVwtstag2TL4HQhAnC8ATf"
_STRIVER = "https://www.youtube.com/@takeUforward"
_STRIVER_A2Z = "https://www.youtube.com/playlist?list=PLgUwDviBIf0oF3FS66l-8uns4RvqaD6BY"

def nc(vid: str) -> str:
    """Return a full YouTube watch URL for a NeetCode video ID."""
    return f"https://www.youtube.com/watch?v={vid}"


def problem(
    title: str,
    slug: str,
    topic: str,
    difficulty: str,
    sub_topic: str,
    estimated_minutes: int,
    tags: list[str],
    youtube_url: str | None = None,
):
    return {
        "title": title,
        "topic": topic,
        "sub_topic": sub_topic,
        "difficulty": difficulty,
        "resource_type": "leetcode",
        "url": f"https://leetcode.com/problems/{slug}/",
        "youtube_url": youtube_url,
        "platform": "leetcode",
        "estimated_minutes": estimated_minutes,
        "tags": tags,
    }


def resource(
    title: str,
    topic: str,
    difficulty: str,
    resource_type: str,
    url: str,
    platform: str,
    sub_topic: str = "",
    estimated_minutes: int | None = None,
    tags: list[str] | None = None,
    youtube_url: str | None = None,
):
    return {
        "title": title,
        "topic": topic,
        "sub_topic": sub_topic or None,
        "difficulty": difficulty,
        "resource_type": resource_type,
        "url": url,
        "youtube_url": youtube_url,
        "platform": platform,
        "estimated_minutes": estimated_minutes,
        "tags": tags or [],
    }


def build_resources():
    resources = [
        # ── Arrays ────────────────────────────────────────────────────────────
        problem("Two Sum", "two-sum", "Arrays", "easy", "Hash Map", 25,
                ["array", "hash-map"], nc("KLlXCFG5TnA")),
        problem("Best Time to Buy and Sell Stock", "best-time-to-buy-and-sell-stock", "Arrays", "easy", "Sliding Window", 25,
                ["array", "greedy"], nc("1pkOgXD63yU")),
        problem("Contains Duplicate", "contains-duplicate", "Arrays", "easy", "Hash Set", 15,
                ["array", "set"], nc("3OamzN90kPg")),
        problem("Product of Array Except Self", "product-of-array-except-self", "Arrays", "medium", "Prefix/Suffix", 35,
                ["array", "prefix"], nc("bNvIQI2wAjk")),
        problem("Maximum Subarray", "maximum-subarray", "Arrays", "medium", "Kadane", 30,
                ["array", "greedy"], nc("5WZl3MMT0Eg")),
        problem("Merge Intervals", "merge-intervals", "Arrays", "medium", "Intervals", 35,
                ["intervals", "sorting"], nc("44H3cEC2fFM")),
        problem("3Sum", "3sum", "Arrays", "medium", "Two Pointers", 40,
                ["array", "two-pointers"], nc("jzZsG8n2R9A")),
        problem("Container With Most Water", "container-with-most-water", "Arrays", "medium", "Two Pointers", 30,
                ["array", "two-pointers"], nc("UuiTKBwPgAo")),
        problem("Longest Consecutive Sequence", "longest-consecutive-sequence", "Arrays", "medium", "Hash Set", 35,
                ["array", "hash-set"], nc("P6RZZMu_maU")),
        problem("Trapping Rain Water", "trapping-rain-water", "Arrays", "hard", "Two Pointers", 50,
                ["array", "two-pointers"], nc("ZI2z5pq0TqA")),

        # ── Strings ───────────────────────────────────────────────────────────
        problem("Valid Anagram", "valid-anagram", "Strings", "easy", "Frequency Count", 15,
                ["string", "hash-map"], nc("9UtInBqnCgA")),
        problem("Group Anagrams", "group-anagrams", "Strings", "medium", "Hashing", 30,
                ["string", "hash-map"], nc("vzdNOK2oB2E")),
        problem("Longest Substring Without Repeating Characters", "longest-substring-without-repeating-characters", "Strings", "medium", "Sliding Window", 35,
                ["string", "sliding-window"], nc("wiGpQwVHdE0")),
        problem("Valid Palindrome", "valid-palindrome", "Strings", "easy", "Two Pointers", 15,
                ["string", "two-pointers"], nc("jJXJ16kPFWg")),
        problem("Longest Palindromic Substring", "longest-palindromic-substring", "Strings", "medium", "Expand Around Center", 35,
                ["string"], nc("XYQecbcd6_c")),
        problem("Palindromic Substrings", "palindromic-substrings", "Strings", "medium", "Expand Around Center", 30,
                ["string"], nc("4RACzI5-du8")),
        problem("Minimum Window Substring", "minimum-window-substring", "Strings", "hard", "Sliding Window", 50,
                ["string", "sliding-window"], nc("jSto0O4AJbM")),
        problem("Find All Anagrams in a String", "find-all-anagrams-in-a-string", "Strings", "medium", "Sliding Window", 35,
                ["string", "sliding-window"], _NC_150),

        # ── Linked List ───────────────────────────────────────────────────────
        problem("Reverse Linked List", "reverse-linked-list", "Linked List", "easy", "Pointers", 20,
                ["linked-list"], nc("G0_I-ZF0S38")),
        problem("Merge Two Sorted Lists", "merge-two-sorted-lists", "Linked List", "easy", "Pointers", 20,
                ["linked-list"], nc("XIdigk956u0")),
        problem("Linked List Cycle", "linked-list-cycle", "Linked List", "easy", "Fast/Slow Pointers", 20,
                ["linked-list", "two-pointers"], nc("gBTe7lFR3vc")),
        problem("Reorder List", "reorder-list", "Linked List", "medium", "Fast/Slow Pointers", 35,
                ["linked-list"], nc("S5bfdUTrKLM")),
        problem("Remove Nth Node From End of List", "remove-nth-node-from-end-of-list", "Linked List", "medium", "Two Pointers", 25,
                ["linked-list", "two-pointers"], nc("XVuQxVej6y8")),
        problem("Add Two Numbers", "add-two-numbers", "Linked List", "medium", "Simulation", 30,
                ["linked-list"], nc("wgFPrzTjm7s")),
        problem("Copy List with Random Pointer", "copy-list-with-random-pointer", "Linked List", "medium", "Hash Map", 40,
                ["linked-list", "hash-map"], nc("5Y2EiZST97Y")),
        problem("LRU Cache", "lru-cache", "Linked List", "medium", "Design", 45,
                ["linked-list", "design", "hash-map"], nc("7ABFKPK2hD4")),

        # ── Stacks & Queues ───────────────────────────────────────────────────
        problem("Valid Parentheses", "valid-parentheses", "Stacks & Queues", "easy", "Stack", 15,
                ["stack"], nc("WTzjTskDFMg")),
        problem("Min Stack", "min-stack", "Stacks & Queues", "medium", "Stack", 25,
                ["stack", "design"], nc("qkLl7nAwDPo")),
        problem("Evaluate Reverse Polish Notation", "evaluate-reverse-polish-notation", "Stacks & Queues", "medium", "Stack", 25,
                ["stack"], nc("iu0082c4HDE")),
        problem("Daily Temperatures", "daily-temperatures", "Stacks & Queues", "medium", "Monotonic Stack", 35,
                ["stack", "monotonic"], nc("cTBiBSnjO3c")),
        problem("Car Fleet", "car-fleet", "Stacks & Queues", "medium", "Stack", 30,
                ["stack", "sorting"], nc("Pr6T-3yB9RM")),
        problem("Largest Rectangle in Histogram", "largest-rectangle-in-histogram", "Stacks & Queues", "hard", "Monotonic Stack", 50,
                ["stack", "monotonic"], nc("zx5Sw9130L0")),

        # ── Binary Trees ──────────────────────────────────────────────────────
        problem("Invert Binary Tree", "invert-binary-tree", "Binary Trees", "easy", "DFS", 15,
                ["tree", "dfs"], nc("OnSn2XEQ4MY")),
        problem("Maximum Depth of Binary Tree", "maximum-depth-of-binary-tree", "Binary Trees", "easy", "DFS", 15,
                ["tree", "dfs"], nc("hTM3phVI6YQ")),
        problem("Diameter of Binary Tree", "diameter-of-binary-tree", "Binary Trees", "easy", "DFS", 25,
                ["tree", "dfs"], nc("bkxqA8Rfv04")),
        problem("Balanced Binary Tree", "balanced-binary-tree", "Binary Trees", "easy", "DFS", 20,
                ["tree", "dfs"], nc("QfJsau0ItOY")),
        problem("Same Tree", "same-tree", "Binary Trees", "easy", "DFS", 15,
                ["tree"], nc("vRbbcKXCxOw")),
        problem("Subtree of Another Tree", "subtree-of-another-tree", "Binary Trees", "easy", "DFS", 25,
                ["tree"], nc("E36O5SWp-LE")),
        problem("Binary Tree Level Order Traversal", "binary-tree-level-order-traversal", "Binary Trees", "medium", "BFS", 25,
                ["tree", "bfs"], nc("6ZnyEApgFYg")),
        problem("Binary Tree Right Side View", "binary-tree-right-side-view", "Binary Trees", "medium", "BFS", 25,
                ["tree", "bfs"], nc("d4zLyf32e3I")),
        problem("Lowest Common Ancestor of a Binary Tree", "lowest-common-ancestor-of-a-binary-tree", "Binary Trees", "medium", "DFS", 35,
                ["tree", "dfs"], nc("gs2LMfuOR9k")),
        problem("Path Sum II", "path-sum-ii", "Binary Trees", "medium", "DFS", 30,
                ["tree", "dfs", "backtracking"], _NC_150),
        problem("Serialize and Deserialize Binary Tree", "serialize-and-deserialize-binary-tree", "Binary Trees", "hard", "BFS", 50,
                ["tree", "design"], nc("u4JAi2JJhI8")),

        # ── BST ───────────────────────────────────────────────────────────────
        problem("Validate Binary Search Tree", "validate-binary-search-tree", "BST", "medium", "Inorder", 30,
                ["bst", "tree"], nc("s6ATEkipzow")),
        problem("Kth Smallest Element in a BST", "kth-smallest-element-in-a-bst", "BST", "medium", "Inorder", 30,
                ["bst", "tree"], nc("5LUXSvjmGCw")),
        problem("Lowest Common Ancestor of a Binary Search Tree", "lowest-common-ancestor-of-a-binary-search-tree", "BST", "medium", "BST", 20,
                ["bst", "tree"], nc("gs2LMfuOR9k")),
        problem("Convert Sorted Array to Binary Search Tree", "convert-sorted-array-to-binary-search-tree", "BST", "easy", "Divide and Conquer", 20,
                ["bst", "tree"], _NC_150),
        problem("Insert into a Binary Search Tree", "insert-into-a-binary-search-tree", "BST", "medium", "BST", 20,
                ["bst", "tree"], _STRIVER_A2Z),
        problem("Delete Node in a BST", "delete-node-in-a-bst", "BST", "medium", "BST", 30,
                ["bst", "tree"], _STRIVER_A2Z),

        # ── Graphs ────────────────────────────────────────────────────────────
        problem("Number of Islands", "number-of-islands", "Graphs", "medium", "BFS/DFS", 35,
                ["graph", "bfs", "dfs"], nc("pV2kpPD66nE")),
        problem("Clone Graph", "clone-graph", "Graphs", "medium", "Graph Traversal", 35,
                ["graph", "dfs"], nc("mQeF6bN8hMk")),
        problem("Max Area of Island", "max-area-of-island", "Graphs", "medium", "DFS", 30,
                ["graph", "dfs"], nc("W8VuDt0eb5c")),
        problem("Pacific Atlantic Water Flow", "pacific-atlantic-water-flow", "Graphs", "medium", "DFS", 40,
                ["graph", "dfs"], nc("s-VkcjyB55w")),
        problem("Course Schedule", "course-schedule", "Graphs", "medium", "Topological Sort", 40,
                ["graph", "topological-sort"], nc("EgI5nU9etnU")),
        problem("Course Schedule II", "course-schedule-ii", "Graphs", "medium", "Topological Sort", 40,
                ["graph", "topological-sort"], nc("Akt3glMQkTI")),
        problem("Rotting Oranges", "rotting-oranges", "Graphs", "medium", "BFS", 25,
                ["graph", "bfs"], nc("y704fEOx0s0")),
        problem("Surrounded Regions", "surrounded-regions", "Graphs", "medium", "DFS", 35,
                ["graph", "dfs"], nc("9z2BunfoZ5Y")),
        problem("Number of Connected Components in an Undirected Graph", "number-of-connected-components-in-an-undirected-graph", "Graphs", "medium", "Union Find", 30,
                ["graph", "union-find"], nc("8f1XPm4WOUc")),
        problem("Graph Valid Tree", "graph-valid-tree", "Graphs", "medium", "Union Find", 30,
                ["graph", "union-find"], nc("bXsUuownnoQ")),
        problem("Word Ladder", "word-ladder", "Graphs", "hard", "BFS", 55,
                ["graph", "bfs"], nc("h9iTnkgv05E")),
        problem("Alien Dictionary", "alien-dictionary", "Graphs", "hard", "Topological Sort", 55,
                ["graph", "topological-sort"], nc("6kTZYvNNyX8")),

        # ── Dynamic Programming ───────────────────────────────────────────────
        problem("Climbing Stairs", "climbing-stairs", "Dynamic Programming", "easy", "1D DP", 20,
                ["dp"], nc("Y0lT9Fck7qI")),
        problem("Min Cost Climbing Stairs", "min-cost-climbing-stairs", "Dynamic Programming", "easy", "1D DP", 25,
                ["dp"], nc("ktmzVWRkMs8")),
        problem("House Robber", "house-robber", "Dynamic Programming", "medium", "1D DP", 30,
                ["dp"], nc("73r3KWiEvyk")),
        problem("House Robber II", "house-robber-ii", "Dynamic Programming", "medium", "1D DP", 35,
                ["dp"], nc("rWAJCfYYOvM")),
        problem("Longest Increasing Subsequence", "longest-increasing-subsequence", "Dynamic Programming", "medium", "Sequence DP", 40,
                ["dp"], nc("cjWnW0hdF1Y")),
        problem("Coin Change", "coin-change", "Dynamic Programming", "medium", "Unbounded Knapsack", 35,
                ["dp"], nc("H9bfqozjoqs")),
        problem("Longest Common Subsequence", "longest-common-subsequence", "Dynamic Programming", "medium", "2D DP", 40,
                ["dp"], nc("Ua0GhsJSlWM")),
        problem("Word Break", "word-break", "Dynamic Programming", "medium", "1D DP", 35,
                ["dp"], nc("Sx9NNgInc3A")),
        problem("Combination Sum IV", "combination-sum-iv", "Dynamic Programming", "medium", "1D DP", 35,
                ["dp"], nc("dw2nMCxG0ik")),
        problem("Decode Ways", "decode-ways", "Dynamic Programming", "medium", "1D DP", 35,
                ["dp"], nc("6aEyTjOwlJU")),
        problem("Unique Paths", "unique-paths", "Dynamic Programming", "medium", "2D DP", 25,
                ["dp"], nc("IlEsdxuD4lY")),
        problem("Jump Game", "jump-game", "Dynamic Programming", "medium", "Greedy/DP", 25,
                ["dp", "greedy"], nc("Yan0cv2cLy8")),
        problem("Partition Equal Subset Sum", "partition-equal-subset-sum", "Dynamic Programming", "medium", "0/1 Knapsack", 40,
                ["dp", "knapsack"], nc("IsvocB5BJhw")),
        problem("Target Sum", "target-sum", "Dynamic Programming", "medium", "0/1 Knapsack", 35,
                ["dp", "backtracking"], nc("g0npyaQtAQM")),
        problem("Edit Distance", "edit-distance", "Dynamic Programming", "medium", "2D DP", 45,
                ["dp", "string"], nc("XYi2-LPfd6s")),
        problem("Maximum Product Subarray", "maximum-product-subarray", "Dynamic Programming", "medium", "1D DP", 30,
                ["dp", "array"], nc("lXVy6YWFcRM")),

        # ── Greedy ────────────────────────────────────────────────────────────
        problem("Jump Game II", "jump-game-ii", "Greedy", "medium", "Greedy", 30,
                ["greedy"], nc("7SBVnw7GSTk")),
        problem("Gas Station", "gas-station", "Greedy", "medium", "Greedy", 30,
                ["greedy"], nc("lJwbPZGo05A")),
        problem("Partition Labels", "partition-labels", "Greedy", "medium", "Greedy", 25,
                ["greedy"], nc("B7m8UmZE-vw")),
        problem("Hand of Straights", "hand-of-straights", "Greedy", "medium", "Greedy", 35,
                ["greedy"], nc("amnrMX4d8zg")),
        problem("Merge Triplets to Form Target Triplet", "merge-triplets-to-form-target-triplet", "Greedy", "medium", "Greedy", 25,
                ["greedy"], nc("IjnS-R44CtM")),
        problem("Task Scheduler", "task-scheduler", "Greedy", "medium", "Greedy", 35,
                ["greedy", "heap"], nc("s8p_-9GV33E")),

        # ── Backtracking ──────────────────────────────────────────────────────
        problem("Subsets", "subsets", "Backtracking", "medium", "Recursion", 25,
                ["backtracking"], nc("REOH22Xwdkk")),
        problem("Subsets II", "subsets-ii", "Backtracking", "medium", "Recursion", 30,
                ["backtracking"], nc("Vn2v6ajA7U0")),
        problem("Combination Sum", "combination-sum", "Backtracking", "medium", "Recursion", 30,
                ["backtracking"], nc("GBKI9VSKdGg")),
        problem("Combination Sum II", "combination-sum-ii", "Backtracking", "medium", "Recursion", 35,
                ["backtracking"], nc("rSA3t6NyoRs")),
        problem("Permutations", "permutations", "Backtracking", "medium", "Recursion", 30,
                ["backtracking"], nc("s7AvT7cGdSo")),
        problem("Word Search", "word-search", "Backtracking", "medium", "Grid DFS", 35,
                ["backtracking", "dfs"], nc("pfiQ_PS1g8E")),
        problem("Palindrome Partitioning", "palindrome-partitioning", "Backtracking", "medium", "Recursion", 35,
                ["backtracking", "dp"], nc("3jvWodd7ht0")),
        problem("N-Queens", "n-queens", "Backtracking", "hard", "Recursion", 55,
                ["backtracking"], nc("Ph95IHmRp5M")),
        problem("Letter Combinations of a Phone Number", "letter-combinations-of-a-phone-number", "Backtracking", "medium", "Recursion", 30,
                ["backtracking"], nc("0snEunYHIoo")),

        # ── Binary Search ─────────────────────────────────────────────────────
        problem("Binary Search", "binary-search", "Binary Search", "easy", "Binary Search", 15,
                ["binary-search"], nc("s4DPM8ct1pI")),
        problem("Search a 2D Matrix", "search-a-2d-matrix", "Binary Search", "medium", "Binary Search", 25,
                ["binary-search"], nc("Ber2pi2C0j0")),
        problem("Koko Eating Bananas", "koko-eating-bananas", "Binary Search", "medium", "Binary Search on Answer", 35,
                ["binary-search"], nc("U2SozAs9RzA")),
        problem("Find Minimum in Rotated Sorted Array", "find-minimum-in-rotated-sorted-array", "Binary Search", "medium", "Binary Search", 25,
                ["binary-search"], nc("nIVW4P8b1VA")),
        problem("Search in Rotated Sorted Array", "search-in-rotated-sorted-array", "Binary Search", "medium", "Binary Search", 30,
                ["binary-search"], nc("U8XENwh8Oy8")),
        problem("Time Based Key-Value Store", "time-based-key-value-store", "Binary Search", "medium", "Binary Search", 30,
                ["binary-search", "design"], nc("fu2cD_Tb81E")),
        problem("Median of Two Sorted Arrays", "median-of-two-sorted-arrays", "Binary Search", "hard", "Binary Search", 55,
                ["binary-search"], nc("q6IEcuVez5k")),

        # ── Heap / Priority Queue ─────────────────────────────────────────────
        problem("Kth Largest Element in an Array", "kth-largest-element-in-an-array", "Heap", "medium", "Heap", 30,
                ["heap"], nc("XEmy13g1Qxc")),
        problem("Top K Frequent Elements", "top-k-frequent-elements", "Heap", "medium", "Heap", 30,
                ["heap"], nc("YPTqKIgVk-k")),
        problem("Find Median from Data Stream", "find-median-from-data-stream", "Heap", "hard", "Two Heaps", 50,
                ["heap"], nc("itmhHWaHupI")),
        problem("Merge k Sorted Lists", "merge-k-sorted-lists", "Heap", "hard", "Heap", 50,
                ["heap", "linked-list"], nc("q5a5OiGbT6Q")),
        problem("Design Twitter", "design-twitter", "Heap", "medium", "Heap + Design", 45,
                ["heap", "design"], nc("pNichitzveg")),
        problem("K Closest Points to Origin", "k-closest-points-to-origin", "Heap", "medium", "Heap", 25,
                ["heap"], nc("rI2EBUEe0qU")),

        # ── SQL ───────────────────────────────────────────────────────────────
        resource("Employees Earning More Than Their Managers", "SQL", "easy", "leetcode",
                 "https://leetcode.com/problems/employees-earning-more-than-their-managers/",
                 "leetcode", "Joins", 20, ["sql", "join"]),
        resource("Duplicate Emails", "SQL", "easy", "leetcode",
                 "https://leetcode.com/problems/duplicate-emails/",
                 "leetcode", "Group By", 15, ["sql", "group-by"]),
        resource("Customers Who Never Order", "SQL", "easy", "leetcode",
                 "https://leetcode.com/problems/customers-who-never-order/",
                 "leetcode", "Subquery", 15, ["sql", "subquery"]),
        resource("Rising Temperature", "SQL", "easy", "leetcode",
                 "https://leetcode.com/problems/rising-temperature/",
                 "leetcode", "Self Join", 20, ["sql", "join"]),
        resource("Nth Highest Salary", "SQL", "medium", "leetcode",
                 "https://leetcode.com/problems/nth-highest-salary/",
                 "leetcode", "Dense Rank", 25, ["sql", "window"]),
        resource("Rank Scores", "SQL", "medium", "leetcode",
                 "https://leetcode.com/problems/rank-scores/",
                 "leetcode", "Window Functions", 25, ["sql", "window"]),
        resource("Department Top Three Salaries", "SQL", "hard", "leetcode",
                 "https://leetcode.com/problems/department-top-three-salaries/",
                 "leetcode", "Window Functions", 35, ["sql", "window"]),

        # ── Learning resources ────────────────────────────────────────────────
        resource("Striver A2Z DSA Course Sheet", "Arrays", "medium", "article",
                 "https://takeuforward.org/strivers-a2z-dsa-course/strivers-a2z-dsa-course-sheet-2/",
                 "takeuforward", "Structured DSA", 180, ["dsa", "sheet"]),
        resource("NeetCode Roadmap", "Arrays", "medium", "article",
                 "https://neetcode.io/roadmap",
                 "neetcode", "Structured DSA", 180, ["dsa", "roadmap"]),
        resource("NeetCode Channel", "Dynamic Programming", "medium", "youtube",
                 "https://www.youtube.com/@NeetCode",
                 "youtube", "Interview Prep", 90, ["youtube", "dsa"]),
        resource("takeUforward Channel (Striver)", "Dynamic Programming", "medium", "youtube",
                 "https://www.youtube.com/@takeUforward",
                 "youtube", "Interview Prep", 90, ["youtube", "dsa"]),
        resource("CodeWithHarry Channel (Hindi)", "Projects", "easy", "youtube",
                 "https://www.youtube.com/@CodeWithHarry",
                 "codewithharry", "Hindi Prep", 90, ["hindi", "programming"]),
        resource("Apna College Channel (Hindi)", "Projects", "easy", "youtube",
                 "https://www.youtube.com/@ApnaCollegeOfficial",
                 "apna college", "Hindi Prep", 90, ["hindi", "programming"]),
        resource("Apna College DSA Playlist (Hindi)", "Arrays", "easy", "youtube",
                 "https://www.youtube.com/playlist?list=PLfqMhTWNBTe3LtFWcvwpqTkUSlB32kJop",
                 "apna college", "Hindi DSA", 300, ["hindi", "dsa"]),
        resource("Gate Smashers DBMS Playlist", "DBMS", "medium", "youtube",
                 "https://www.youtube.com/playlist?list=PLxCzCOWd7aiFAN6I8CuViBuCdJgiOkT2Y",
                 "youtube", "DBMS", 240, ["dbms"]),
        resource("Gate Smashers Operating Systems Playlist", "Operating Systems", "medium", "youtube",
                 "https://www.youtube.com/playlist?list=PLxCzCOWd7aiGz9donHRrE9I3Mwn6XdP8p",
                 "youtube", "OS", 240, ["os"]),
        resource("Gate Smashers Computer Networks Playlist", "Computer Networks", "medium", "youtube",
                 "https://www.youtube.com/playlist?list=PLxCzCOWd7aiGCMCFqBLKktgcuv9XmDFHt",
                 "youtube", "CN", 240, ["networking"]),
        resource("GFG DBMS Tutorial", "DBMS", "easy", "article",
                 "https://www.geeksforgeeks.org/dbms/",
                 "geeksforgeeks", "DBMS", 120, ["dbms"]),
        resource("GFG Operating Systems", "Operating Systems", "easy", "article",
                 "https://www.geeksforgeeks.org/operating-systems/",
                 "geeksforgeeks", "OS", 120, ["os"]),
        resource("GFG Computer Networks", "Computer Networks", "easy", "article",
                 "https://www.geeksforgeeks.org/computer-network-tutorials/",
                 "geeksforgeeks", "CN", 120, ["networking"]),
        resource("GFG OOP in Java", "OOP", "easy", "article",
                 "https://www.geeksforgeeks.org/object-oriented-programming-oops-concept-in-java/",
                 "geeksforgeeks", "OOP", 90, ["oop"]),
        resource("Striver OOP Playlist", "OOP", "medium", "youtube",
                 "https://www.youtube.com/playlist?list=PLgUwDviBIf0p4ozDR_kJJkONnb1wdx2Ma",
                 "takeuforward", "OOP", 180, ["oop"]),
        resource("IndiaBIX Aptitude", "Aptitude", "easy", "practice",
                 "https://www.indiabix.com/",
                 "indiabix", "Aptitude", 90, ["aptitude"]),
        resource("PrepInsta Company Preparation", "Aptitude", "medium", "article",
                 "https://prepinsta.com/",
                 "prepinsta", "Placement Prep", 90, ["placement"]),
        resource("Frontend Mentor Challenges", "Projects", "easy", "practice",
                 "https://www.frontendmentor.io/challenges",
                 "frontendmentor", "Projects", 120, ["project", "frontend"]),
        resource("Roadmap.sh Computer Science", "OOP", "easy", "article",
                 "https://roadmap.sh/computer-science",
                 "roadmap.sh", "CS Roadmap", 120, ["roadmap"]),
        resource("Roadmap.sh Backend", "SQL", "easy", "article",
                 "https://roadmap.sh/backend",
                 "roadmap.sh", "Backend", 120, ["backend"]),
        resource("HackerRank Interview Prep Kit", "Aptitude", "medium", "practice",
                 "https://www.hackerrank.com/interview/interview-preparation-kit",
                 "hackerrank", "Interview Prep", 90, ["coding-test"]),
        resource("CodeChef Practice", "Aptitude", "medium", "practice",
                 "https://www.codechef.com/practice",
                 "codechef", "Interview Prep", 90, ["coding-test"]),
        resource("SQL ZOO Tutorial", "SQL", "easy", "practice",
                 "https://sqlzoo.net/wiki/SQL_Tutorial",
                 "sqlzoo", "SQL Practice", 120, ["sql"]),
        resource("Mode SQL Tutorial", "SQL", "medium", "article",
                 "https://mode.com/sql-tutorial/",
                 "mode", "SQL Practice", 90, ["sql"]),
        resource("Striver SQL Sheet", "SQL", "medium", "article",
                 "https://takeuforward.org/sql/sql-for-interview/",
                 "takeuforward", "SQL Practice", 120, ["sql"]),
    ]

    return resources


def upsert_resources():
    db = SessionLocal()
    try:
        seeded = 0
        updated = 0
        for item in build_resources():
            existing = db.query(Resource).filter(Resource.url == item["url"]).first()
            if existing:
                for key, value in item.items():
                    setattr(existing, key, value)
                updated += 1
            else:
                db.add(Resource(**item))
                seeded += 1

        db.commit()
        print(f"Resource seed complete. inserted={seeded} updated={updated}")
    finally:
        db.close()


if __name__ == "__main__":
    upsert_resources()
