"use client";

import { useEffect, useState } from "react";
import { roadmapApi } from "@/lib/api";
import type { Roadmap } from "@/types";
import {
  Map,
  Loader2,
  Sparkles,
  ChevronDown,
  ChevronRight,
  CheckCircle2,
  Clock,
  BookOpen,
  Code,
  FileText,
  MessageSquare,
  Zap,
} from "lucide-react";

const TYPE_ICONS: Record<string, React.ReactNode> = {
  learn: <BookOpen className="h-3.5 w-3.5" />,
  practice: <Code className="h-3.5 w-3.5" />,
  review: <FileText className="h-3.5 w-3.5" />,
  interview: <MessageSquare className="h-3.5 w-3.5" />,
  project: <Zap className="h-3.5 w-3.5" />,
  quiz: <CheckCircle2 className="h-3.5 w-3.5" />,
};

export default function RoadmapPage() {
  const [roadmap, setRoadmap] = useState<Roadmap | null>(null);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [generatingWeek, setGeneratingWeek] = useState<number | null>(null);
  const [totalWeeksToGen, setTotalWeeksToGen] = useState(0);
  const [expandedWeek, setExpandedWeek] = useState<number | null>(null);
  const [error, setError] = useState("");

  useEffect(() => {
    loadRoadmap();
  }, []);

  async function loadRoadmap() {
    try {
      const rm = await roadmapApi.getActive();
      setRoadmap(rm);
      setExpandedWeek(rm.current_week - 1);
    } catch {
      setRoadmap(null);
    } finally {
      setLoading(false);
    }
  }

  async function handleGenerate() {
    setGenerating(true);
    setGeneratingWeek(null);
    setTotalWeeksToGen(0);
    setError("");
    try {
      // Step 1: Generate plan + Week 1
      const rm = await roadmapApi.generate();
      setRoadmap(rm);
      setExpandedWeek(0);

      // Step 2: Generate remaining weeks sequentially
      const pendingWeeks = rm.content.weeks
        .filter((w) => w.pending || (!w.days?.length))
        .map((w) => w.week);

      if (pendingWeeks.length > 0) {
        setTotalWeeksToGen(pendingWeeks.length);
        let latestRm = rm;
        for (const weekNum of pendingWeeks) {
          setGeneratingWeek(weekNum);
          try {
            latestRm = await roadmapApi.generateWeek(rm.id, weekNum);
            setRoadmap(latestRm);
          } catch (weekErr) {
            console.error(`Failed to generate week ${weekNum}:`, weekErr);
            // Continue with remaining weeks even if one fails
          }
        }
        setGeneratingWeek(null);
        setTotalWeeksToGen(0);
      }
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to generate roadmap");
    } finally {
      setGenerating(false);
      setGeneratingWeek(null);
      setTotalWeeksToGen(0);
    }
  }

  if (loading) {
    return (
      <div className="flex h-64 items-center justify-center">
        <div className="rounded-xl px-8 py-6 text-center card-glass pulse-card">
          <Loader2 className="mx-auto h-8 w-8 animate-spin text-primary spinner-glow" />
          <p className="mt-3 text-micro text-muted-foreground">Loading roadmap nodes...</p>
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-6 animate-fade-in">
      <div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between">
        <div>
          <h1 className="heading-lg font-bold flex items-center gap-2">
            <Map className="h-6 w-6 text-primary" />
            Your Roadmap
          </h1>
          <p className="mt-1 text-muted-foreground body-text">
            Personalized learning path generated by AI
          </p>
        </div>
        <button
          onClick={handleGenerate}
          disabled={generating}
          className="flex w-full items-center justify-center gap-2 rounded-lg px-4 py-2.5 text-sm font-semibold disabled:opacity-60 sm:w-auto btn-accent"
        >
          {generating ? (
            <>
              <Loader2 className="h-4 w-4 animate-spin spinner-glow" />
              {generatingWeek
                ? `Generating Week ${generatingWeek}...`
                : "Creating Plan..."}
            </>
          ) : (
            <>
              <Sparkles className="h-4 w-4" />
              {roadmap ? "Regenerate" : "Generate Roadmap"}
            </>
          )}
        </button>
      </div>

      {error && (
        <div className="rounded-lg bg-destructive/10 p-4 text-sm text-destructive">
          {error}
        </div>
      )}

      {/* Generation progress */}
      {generating && generatingWeek && totalWeeksToGen > 0 && roadmap && (
        <div className="rounded-xl p-4 card-dark">
          <div className="mb-2 flex items-center justify-between text-sm">
            <span className="font-medium flex items-center gap-2">
              <Loader2 className="h-4 w-4 animate-spin text-primary spinner-glow" />
              Generating Week {generatingWeek} of {roadmap.total_weeks}
            </span>
            <span className="text-muted-foreground tabular-nums">
              {Math.round(((generatingWeek - 1) / roadmap.total_weeks) * 100)}%
            </span>
          </div>
          <div className="h-2.5 rounded-full bg-muted">
            <div
              className="h-2.5 rounded-full bg-gradient-to-r from-primary to-amber-600 transition-all duration-500"
              style={{
                width: `${((generatingWeek - 1) / roadmap.total_weeks) * 100}%`,
              }}
            />
          </div>
        </div>
      )}

      {roadmap ? (
        <div className="space-y-4">
          {/* Progress bar */}
          <div className="rounded-xl p-4 card-dark">
            <div className="mb-2 flex items-center justify-between text-sm">
              <span className="font-medium">
                Week {roadmap.current_week} of {roadmap.total_weeks}
              </span>
              <span className="text-muted-foreground tabular-nums">
                {Math.round(((roadmap.current_week - 1) / roadmap.total_weeks) * 100)}% complete
              </span>
            </div>
            <div className="h-2.5 rounded-full bg-muted">
              <div
                className="h-2.5 rounded-full bg-gradient-to-r from-primary to-amber-600 transition-all"
                style={{
                  width: `${((roadmap.current_week - 1) / roadmap.total_weeks) * 100}%`,
                }}
              />
            </div>
          </div>

          {/* Week list */}
          <div className="space-y-3">
            {roadmap.content.weeks?.map((week, index) => {
              const isExpanded = expandedWeek === index;
              const isCurrent = index === roadmap.current_week - 1;
              const isPast = index < roadmap.current_week - 1;
              const isPending = week.pending || !week.days?.length;
              const isGeneratingThis = generatingWeek === week.week;

              return (
                <div
                  key={index}
                  className={`rounded-xl border transition ${
                    isCurrent
                      ? "border-primary/50 bg-primary/10 card-glass"
                      : isPast
                      ? "border-primary/30 bg-primary/5 card-glass"
                      : isPending
                      ? "border-border/30 bg-card/50 card-dark opacity-75"
                      : "border-border/50 bg-card card-dark"
                  }`}
                >
                  <button
                    onClick={() => !isPending && setExpandedWeek(isExpanded ? null : index)}
                    disabled={isPending}
                    className="flex w-full items-center gap-3 p-3.5 sm:p-4 text-left disabled:cursor-default"
                  >
                    <div
                      className={`flex h-8 w-8 items-center justify-center rounded-full text-xs font-bold ${
                        isPast
                          ? "bg-primary text-primary-foreground"
                          : isCurrent
                          ? "bg-primary text-primary-foreground"
                          : isPending
                          ? "bg-muted/50 text-muted-foreground"
                          : "bg-muted text-muted-foreground"
                      }`}
                    >
                      {isGeneratingThis ? (
                        <Loader2 className="h-4 w-4 animate-spin" />
                      ) : isPast ? (
                        <CheckCircle2 className="h-4 w-4" />
                      ) : (
                        index + 1
                      )}
                    </div>
                    <div className="flex-1 min-w-0">
                      <p className="font-semibold text-sm sm:text-[15px]">
                        Week {week.week || index + 1}: {week.title}
                      </p>
                      {week.description && (
                        <p className="text-xs text-muted-foreground truncate">
                          {week.description}
                        </p>
                      )}
                      {isPending && !isGeneratingThis && (
                        <p className="text-xs text-muted-foreground/60 italic">
                          Waiting to generate...
                        </p>
                      )}
                      {isGeneratingThis && (
                        <p className="text-xs text-primary/80 italic">
                          Generating tasks...
                        </p>
                      )}
                    </div>
                    {isCurrent && (
                      <span className="rounded-full bg-primary/20 px-2 py-0.5 text-xs font-medium text-primary">
                        Current
                      </span>
                    )}
                    {isExpanded ? (
                      <ChevronDown className="h-4 w-4 text-muted-foreground" />
                    ) : (
                      <ChevronRight className="h-4 w-4 text-muted-foreground" />
                    )}
                  </button>

                  {isExpanded && !isPending && week.days && (
                    <div className="border-t border-border/30 px-4 pb-4">
                      {week.days.map((day, dayIndex) => (
                        <div key={dayIndex} className="mt-4">
                          <p className="mb-2 text-xs font-semibold text-muted-foreground uppercase">
                            Day {day.day || dayIndex + 1}
                            {day.title ? ` - ${day.title}` : ""}
                          </p>
                          <div className="space-y-2">
                            {day.tasks?.map((task, ti) => (
                              <div
                                key={task.id || ti}
                                className="flex items-start gap-3 rounded-lg border border-border/30 bg-background p-3 card-glass"
                              >
                                <div className="mt-0.5 text-muted-foreground">
                                  {TYPE_ICONS[task.type] || <BookOpen className="h-3.5 w-3.5" />}
                                </div>
                                <div className="flex-1 min-w-0">
                                  <p className="text-sm font-medium">{task.title}</p>
                                  {task.description && (
                                    <p className="text-xs text-muted-foreground mt-0.5">
                                      {task.description}
                                    </p>
                                  )}
                                </div>
                                <div className="flex items-center gap-2">
                                  {task.duration_minutes && (
                                    <span className="flex items-center gap-1 text-xs text-muted-foreground">
                                      <Clock className="h-3 w-3" />
                                      {task.duration_minutes}m
                                    </span>
                                  )}
                                  <span className={`rounded-full px-2 py-0.5 text-[10px] font-medium capitalize ${
                                    task.type === "learn"
                                      ? "bg-primary/20 text-primary"
                                      : task.type === "practice"
                                      ? "bg-amber-500/15 text-amber-700 dark:text-amber-300"
                                      : task.type === "interview"
                                      ? "bg-orange-500/15 text-orange-700 dark:text-orange-300"
                                      : "bg-secondary text-secondary-foreground"
                                  }`}>
                                    {task.type}
                                  </span>
                                </div>
                              </div>
                            ))}
                          </div>
                        </div>
                      ))}
                    </div>
                  )}
                </div>
              );
            })}
          </div>
        </div>
      ) : (
        <div className="flex flex-col items-center justify-center rounded-2xl border border-dashed border-border py-16 text-center card-dark">
          <Map className="mb-4 h-12 w-12 text-muted-foreground" />
          <h2 className="mb-2 text-xl font-semibold">No Roadmap Yet</h2>
          <p className="mb-6 max-w-md text-sm text-muted-foreground">
            Click &quot;Generate Roadmap&quot; to create a personalized learning path
            based on your profile, target role, and skill level.
          </p>
        </div>
      )}
    </div>
  );
}
