"use client";

import { useEffect, useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { roadmapApi } from "@/lib/api";
import type { Roadmap } from "@/types";
import { BlurFade } from "@/components/magic/BlurFade";
import { ShimmerButton } from "@/components/magic/ShimmerButton";
import {
  Map,
  Loader2,
  Sparkles,
  ChevronDown,
  ChevronRight,
  CheckCircle2,
  BookOpen,
  Code,
  FileText,
  MessageSquare,
  Zap,
} from "lucide-react";

const TYPE_ICONS: Record<string, React.ReactNode> = {
  learn: <BookOpen className="h-3.5 w-3.5" />,
  practice: <Code className="h-3.5 w-3.5" />,
  review: <FileText className="h-3.5 w-3.5" />,
  interview: <MessageSquare className="h-3.5 w-3.5" />,
  project: <Zap className="h-3.5 w-3.5" />,
  quiz: <CheckCircle2 className="h-3.5 w-3.5" />,
};

export default function RoadmapPage() {
  const [roadmap, setRoadmap] = useState<Roadmap | null>(null);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [generatingWeek, setGeneratingWeek] = useState<number | null>(null);
  const [totalWeeksToGen, setTotalWeeksToGen] = useState(0);
  const [expandedWeek, setExpandedWeek] = useState<number | null>(null);
  const [expandedDay, setExpandedDay] = useState<string | null>(null);
  const [error, setError] = useState("");

  useEffect(() => {
    loadRoadmap();
  }, []);

  async function loadRoadmap() {
    try {
      const rm = await roadmapApi.getActive();
      setRoadmap(rm);
      setExpandedWeek(rm.current_week - 1);
    } catch {
      setRoadmap(null);
    } finally {
      setLoading(false);
    }
  }

  async function handleGenerate() {
    setGenerating(true);
    setGeneratingWeek(null);
    setTotalWeeksToGen(0);
    setError("");
    try {
      const rm = await roadmapApi.generate();
      setRoadmap(rm);
      setExpandedWeek(0);

      const pendingWeeks = rm.content.weeks.filter((w) => w.pending || !w.days?.length).map((w) => w.week);

      if (pendingWeeks.length > 0) {
        setTotalWeeksToGen(pendingWeeks.length);
        let latestRm = rm;
        for (const weekNum of pendingWeeks) {
          setGeneratingWeek(weekNum);
          try {
            latestRm = await roadmapApi.generateWeek(rm.id, weekNum);
            setRoadmap(latestRm);
          } catch (weekErr) {
            console.error(`Failed to generate week ${weekNum}:`, weekErr);
          }
        }
        setGeneratingWeek(null);
        setTotalWeeksToGen(0);
      }
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to generate roadmap");
    } finally {
      setGenerating(false);
      setGeneratingWeek(null);
      setTotalWeeksToGen(0);
    }
  }

  if (loading) {
    return (
      <div className="flex h-64 items-center justify-center">
        <div className="rounded-xl px-8 py-6 text-center card-glass pulse-card">
          <Loader2 className="mx-auto h-8 w-8 animate-spin text-primary spinner-glow" />
          <p className="mt-3 text-micro text-muted-foreground">Loading roadmap nodes...</p>
        </div>
      </div>
    );
  }

  return (
    <motion.div className="space-y-6" initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ duration: 0.4 }}>
      <div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between">
        <div>
          <h1 className="heading-lg font-bold">Your Learning Roadmap</h1>
          <p className="body-text mt-1 text-muted-foreground">
            {roadmap
              ? `Target Role: ${roadmap.target_role?.replace(/_/g, " ") || "SDE at Amazon"} • Estimated Completion: ${roadmap.total_weeks} Weeks`
              : "Personalized learning path generated by AI"}
          </p>
        </div>
        <ShimmerButton onClick={handleGenerate} disabled={generating} className="w-full sm:w-auto">
          {generating ? (
            <>
              <Loader2 className="h-4 w-4 animate-spin spinner-glow" />
              {generatingWeek ? `Generating Week ${generatingWeek}...` : "Creating Plan..."}
            </>
          ) : (
            <>
              <Sparkles className="h-4 w-4" />
              {roadmap ? "Recalculate Schedule" : "Generate Roadmap"}
            </>
          )}
        </ShimmerButton>
      </div>

      {error && <div className="rounded-lg bg-destructive/10 p-4 text-sm text-destructive">{error}</div>}

      {generating && generatingWeek && totalWeeksToGen > 0 && roadmap && (
        <div className="rounded-xl p-4 card-dark">
          <div className="mb-2 flex items-center justify-between text-sm">
            <span className="flex items-center gap-2 font-medium">
              <Loader2 className="h-4 w-4 animate-spin text-primary spinner-glow" />
              Generating Week {generatingWeek} of {roadmap.total_weeks}
            </span>
            <span className="tabular-nums text-muted-foreground">
              {Math.round(((generatingWeek - 1) / roadmap.total_weeks) * 100)}%
            </span>
          </div>
          <div className="h-2.5 rounded-full bg-muted">
            <motion.div
              className="h-2.5 rounded-full bg-gradient-to-r from-primary to-amber-600"
              initial={{ width: 0 }}
              animate={{ width: `${((generatingWeek - 1) / roadmap.total_weeks) * 100}%` }}
              transition={{ type: "spring", stiffness: 120, damping: 20 }}
            />
          </div>
        </div>
      )}

      {roadmap ? (
        <div className="space-y-4">
          <div className="relative">
            <div className="absolute bottom-8 left-[19px] top-8 w-[2px] bg-border">
              <motion.div
                className="w-full origin-top bg-primary"
                initial={{ scaleY: 0 }}
                animate={{ scaleY: (roadmap.current_week - 1) / roadmap.content.weeks.length }}
                transition={{ type: "spring", stiffness: 120, damping: 22 }}
                style={{ height: "100%" }}
              />
            </div>

            <div className="space-y-4">
              {roadmap.content.weeks?.map((week, index) => {
                const isExpanded = expandedWeek === index;
                const isCurrent = index === roadmap.current_week - 1;
                const isPast = index < roadmap.current_week - 1;
                const isPending = week.pending || !week.days?.length;
                const isGeneratingThis = generatingWeek === week.week;
                const allTasks = week.days?.flatMap((d) => d.tasks || []) || [];
                const completedTasks = allTasks.filter((t) => t.completed).length;
                const weekProgress = allTasks.length > 0 ? Math.round((completedTasks / allTasks.length) * 100) : 0;

                return (
                  <BlurFade key={index} delay={index * 0.1}>
                    <div
                      className={`relative rounded-2xl border transition ${
                        isCurrent
                          ? "border-primary/50 bg-gradient-to-br from-primary/10 to-transparent"
                          : isPast
                            ? "border-primary/30 bg-primary/5"
                            : isPending
                              ? "border-border/30 bg-card/50 opacity-75"
                              : "border-border/50 bg-card"
                      }`}
                    >
                      <button
                        onClick={() => !isPending && setExpandedWeek(isExpanded ? null : index)}
                        disabled={isPending}
                        className="flex w-full items-start gap-4 p-5 text-left disabled:cursor-default"
                      >
                        <div className="relative flex-shrink-0">
                          <div
                            className={`flex h-10 w-10 items-center justify-center rounded-full text-sm font-bold transition ${
                              isPast
                                ? "bg-primary text-primary-foreground"
                                : isCurrent
                                  ? "bg-primary text-primary-foreground ring-4 ring-primary/20"
                                  : isPending
                                    ? "bg-muted/50 text-muted-foreground"
                                    : "bg-muted text-muted-foreground"
                            }`}
                          >
                            {isGeneratingThis ? (
                              <Loader2 className="h-5 w-5 animate-spin" />
                            ) : isPast ? (
                              <CheckCircle2 className="h-5 w-5" />
                            ) : (
                              index + 1
                            )}
                          </div>
                        </div>

                        <div className="min-w-0 flex-1">
                          <div className="flex items-start justify-between gap-3">
                            <div className="min-w-0 flex-1">
                              <div className="flex items-center gap-2">
                                <span className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">
                                  Weeks {week.week || index + 1}
                                </span>
                                {isCurrent && (
                                  <span className="rounded-full bg-primary px-2 py-0.5 text-[10px] font-bold text-primary-foreground">
                                    CURRENT
                                  </span>
                                )}
                              </div>
                              <p className="mt-1 text-base font-semibold sm:text-lg">{week.title}</p>
                              {week.description && <p className="mt-1 text-sm text-muted-foreground">{week.description}</p>}
                              {isPending && !isGeneratingThis && (
                                <p className="mt-1 text-xs italic text-muted-foreground/60">Waiting to generate...</p>
                              )}
                              {isGeneratingThis && <p className="mt-1 text-xs italic text-primary/80">Generating tasks...</p>}
                            </div>

                            <div className="flex items-center gap-2">
                              {!isPending && (
                                <>
                                  {allTasks.length > 0 && (
                                    <div className="hidden sm:block">
                                      <div className="mb-1 text-xs text-muted-foreground">Progress</div>
                                      <div className="flex items-center gap-2">
                                        <div className="h-2 w-24 rounded-full bg-muted">
                                          <motion.div
                                            className="h-2 rounded-full bg-primary"
                                            initial={{ width: 0 }}
                                            animate={{ width: `${weekProgress}%` }}
                                            transition={{ type: "spring", stiffness: 120, damping: 20, delay: index * 0.06 }}
                                          />
                                        </div>
                                        <span className="text-xs font-semibold tabular-nums">{weekProgress}%</span>
                                      </div>
                                    </div>
                                  )}
                                  {isExpanded ? (
                                    <ChevronDown className="h-5 w-5 text-muted-foreground" />
                                  ) : (
                                    <ChevronRight className="h-5 w-5 text-muted-foreground" />
                                  )}
                                </>
                              )}
                            </div>
                          </div>
                        </div>
                      </button>

                      <AnimatePresence initial={false}>
                        {isExpanded && !isPending && week.days && (
                          <motion.div
                            initial={{ height: 0, opacity: 0 }}
                            animate={{ height: "auto", opacity: 1 }}
                            exit={{ height: 0, opacity: 0 }}
                            transition={{ type: "spring", stiffness: 200, damping: 24 }}
                            className="overflow-hidden border-t border-border/30"
                          >
                            <div className="space-y-5 px-5 pb-5 pt-4">
                              <h4 className="text-sm font-semibold uppercase tracking-wide text-muted-foreground">Modules</h4>
                              {week.days.map((day, dayIndex) => {
                                const dayKey = `w${index}-d${dayIndex}`;
                                const isDayExpanded = expandedDay === dayKey;
                                const allTasksCompleted = day.tasks?.length > 0 && day.tasks.every((t) => t.completed);
                                const someTasksCompleted = day.tasks?.some((t) => t.completed);
                                const completedCount = day.tasks?.filter((t) => t.completed).length || 0;
                                const totalTasks = day.tasks?.length || 0;

                                return (
                                  <motion.div
                                    key={dayIndex}
                                    initial={{ opacity: 0, y: 10 }}
                                    animate={{ opacity: 1, y: 0 }}
                                    transition={{ delay: dayIndex * 0.05 }}
                                    className="space-y-3"
                                  >
                                    <button
                                      className="m-[-0.5rem] flex w-full items-center gap-3 rounded-lg p-2 text-left transition hover:bg-muted/30"
                                      onClick={() => setExpandedDay(isDayExpanded ? null : dayKey)}
                                    >
                                      <div
                                        className={`flex h-6 w-6 flex-shrink-0 items-center justify-center rounded-full text-xs font-bold ${
                                          allTasksCompleted
                                            ? "bg-primary text-primary-foreground"
                                            : someTasksCompleted
                                              ? "border-2 border-primary bg-transparent text-primary"
                                              : "bg-muted text-muted-foreground"
                                        }`}
                                      >
                                        {allTasksCompleted ? <CheckCircle2 className="h-4 w-4" /> : dayIndex + 1}
                                      </div>
                                      <div className="min-w-0 flex-1">
                                        <p className="text-sm font-semibold">{day.title || `Day ${day.day || dayIndex + 1}`}</p>
                                        {totalTasks > 0 && (
                                          <p className="text-xs text-muted-foreground">
                                            {completedCount}/{totalTasks} tasks completed
                                          </p>
                                        )}
                                      </div>
                                      <div className="flex items-center gap-2">
                                        {totalTasks > 0 && (
                                          <span className="tabular-nums text-xs text-muted-foreground">
                                            {day.tasks.reduce((sum, t) => sum + (t.duration_minutes || 0), 0)}m
                                          </span>
                                        )}
                                        {isDayExpanded ? (
                                          <ChevronDown className="h-4 w-4 text-muted-foreground" />
                                        ) : (
                                          <ChevronRight className="h-4 w-4 text-muted-foreground" />
                                        )}
                                      </div>
                                    </button>

                                    <AnimatePresence initial={false}>
                                      {isDayExpanded && day.tasks && (
                                        <motion.div
                                          initial={{ height: 0, opacity: 0 }}
                                          animate={{ height: "auto", opacity: 1 }}
                                          exit={{ height: 0, opacity: 0 }}
                                          transition={{ type: "spring", stiffness: 220, damping: 22 }}
                                          className="overflow-hidden"
                                        >
                                          <div className="ml-9 space-y-3 border-l-2 border-border pl-4">
                                            {day.tasks.map((task, ti) => (
                                              <motion.div
                                                key={task.id || ti}
                                                initial={{ opacity: 0, y: 10 }}
                                                animate={{ opacity: 1, y: 0 }}
                                                transition={{ delay: ti * 0.05 }}
                                                className="space-y-1.5"
                                              >
                                                <div className="flex items-start gap-2 text-sm">
                                                  <div className={`mt-0.5 ${task.completed ? "text-primary" : "text-muted-foreground"}`}>
                                                    {task.completed ? (
                                                      <CheckCircle2 className="h-3.5 w-3.5" />
                                                    ) : (
                                                      TYPE_ICONS[task.type] || <BookOpen className="h-3.5 w-3.5" />
                                                    )}
                                                  </div>
                                                  <div className="min-w-0 flex-1">
                                                    <p className={`font-medium ${task.completed ? "line-through text-muted-foreground" : ""}`}>
                                                      {task.title}
                                                    </p>
                                                    {task.description && (
                                                      <p className="mt-0.5 text-xs text-muted-foreground">{task.description}</p>
                                                    )}
                                                  </div>
                                                  <div className="flex flex-shrink-0 items-center gap-2">
                                                    <span className="rounded-full bg-muted px-2 py-0.5 text-[10px] font-medium capitalize">
                                                      {task.type}
                                                    </span>
                                                    {task.duration_minutes && (
                                                      <span className="whitespace-nowrap tabular-nums text-xs text-muted-foreground">
                                                        {task.duration_minutes}m
                                                      </span>
                                                    )}
                                                  </div>
                                                </div>
                                                {task.resources && task.resources.length > 0 && (
                                                  <div className="ml-5 flex flex-wrap gap-2">
                                                    {task.resources.map((res, ri) =>
                                                      res.url ? (
                                                        <a
                                                          key={ri}
                                                          href={res.url}
                                                          target="_blank"
                                                          rel="noopener noreferrer"
                                                          className="inline-flex items-center gap-1 rounded-md border border-border px-2 py-0.5 text-[11px] font-medium text-primary transition hover:bg-primary/10"
                                                        >
                                                          <BookOpen className="h-3 w-3" />
                                                          {res.title}
                                                        </a>
                                                      ) : (
                                                        <span
                                                          key={ri}
                                                          className="inline-flex items-center gap-1 rounded-md bg-muted px-2 py-0.5 text-[11px] font-medium text-muted-foreground"
                                                        >
                                                          <BookOpen className="h-3 w-3" />
                                                          {res.title}
                                                        </span>
                                                      ),
                                                    )}
                                                  </div>
                                                )}
                                              </motion.div>
                                            ))}
                                          </div>
                                        </motion.div>
                                      )}
                                    </AnimatePresence>
                                  </motion.div>
                                );
                              })}
                            </div>
                          </motion.div>
                        )}
                      </AnimatePresence>
                    </div>
                  </BlurFade>
                );
              })}
            </div>
          </div>
        </div>
      ) : (
        <div className="flex flex-col items-center justify-center rounded-2xl border border-dashed border-border py-16 text-center card-dark">
          <Map className="mb-4 h-12 w-12 text-muted-foreground" />
          <h2 className="mb-2 text-xl font-semibold">No Roadmap Yet</h2>
          <p className="mb-6 max-w-md text-sm text-muted-foreground">
            Click &quot;Generate Roadmap&quot; to create a personalized learning path based on your profile,
            target role, and skill level.
          </p>
        </div>
      )}
    </motion.div>
  );
}
