"use client";

import { useEffect, useState } from "react";
import { roadmapApi } from "@/lib/api";
import type { Roadmap } from "@/types";
import {
  Map,
  Loader2,
  Sparkles,
  ChevronDown,
  ChevronRight,
  CheckCircle2,
  Clock,
  BookOpen,
  Code,
  FileText,
  MessageSquare,
  Zap,
} from "lucide-react";

const TYPE_ICONS: Record<string, React.ReactNode> = {
  learn: <BookOpen className="h-3.5 w-3.5" />,
  practice: <Code className="h-3.5 w-3.5" />,
  review: <FileText className="h-3.5 w-3.5" />,
  interview: <MessageSquare className="h-3.5 w-3.5" />,
  project: <Zap className="h-3.5 w-3.5" />,
  quiz: <CheckCircle2 className="h-3.5 w-3.5" />,
};

export default function RoadmapPage() {
  const [roadmap, setRoadmap] = useState<Roadmap | null>(null);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [generatingWeek, setGeneratingWeek] = useState<number | null>(null);
  const [totalWeeksToGen, setTotalWeeksToGen] = useState(0);
  const [expandedWeek, setExpandedWeek] = useState<number | null>(null);
  const [error, setError] = useState("");

  useEffect(() => {
    loadRoadmap();
  }, []);

  async function loadRoadmap() {
    try {
      const rm = await roadmapApi.getActive();
      setRoadmap(rm);
      setExpandedWeek(rm.current_week - 1);
    } catch {
      setRoadmap(null);
    } finally {
      setLoading(false);
    }
  }

  async function handleGenerate() {
    setGenerating(true);
    setGeneratingWeek(null);
    setTotalWeeksToGen(0);
    setError("");
    try {
      // Step 1: Generate plan + Week 1
      const rm = await roadmapApi.generate();
      setRoadmap(rm);
      setExpandedWeek(0);

      // Step 2: Generate remaining weeks sequentially
      const pendingWeeks = rm.content.weeks
        .filter((w) => w.pending || (!w.days?.length))
        .map((w) => w.week);

      if (pendingWeeks.length > 0) {
        setTotalWeeksToGen(pendingWeeks.length);
        let latestRm = rm;
        for (const weekNum of pendingWeeks) {
          setGeneratingWeek(weekNum);
          try {
            latestRm = await roadmapApi.generateWeek(rm.id, weekNum);
            setRoadmap(latestRm);
          } catch (weekErr) {
            console.error(`Failed to generate week ${weekNum}:`, weekErr);
            // Continue with remaining weeks even if one fails
          }
        }
        setGeneratingWeek(null);
        setTotalWeeksToGen(0);
      }
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to generate roadmap");
    } finally {
      setGenerating(false);
      setGeneratingWeek(null);
      setTotalWeeksToGen(0);
    }
  }

  if (loading) {
    return (
      <div className="flex h-64 items-center justify-center">
        <div className="rounded-xl px-8 py-6 text-center card-glass pulse-card">
          <Loader2 className="mx-auto h-8 w-8 animate-spin text-primary spinner-glow" />
          <p className="mt-3 text-micro text-muted-foreground">Loading roadmap nodes...</p>
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-6 animate-fade-in">
      <div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between">
        <div>
          <h1 className="heading-lg font-bold">Your Learning Roadmap</h1>
          <p className="mt-1 text-muted-foreground body-text">
            {roadmap 
              ? `Target Role: ${roadmap.target_role?.replace(/_/g, " ") || "SDE at Amazon"} • Estimated Completion: ${roadmap.total_weeks} Weeks`
              : "Personalized learning path generated by AI"
            }
          </p>
        </div>
        <button
          onClick={handleGenerate}
          disabled={generating}
          className="flex w-full items-center justify-center gap-2 rounded-lg px-4 py-2.5 text-sm font-semibold disabled:opacity-60 sm:w-auto btn-accent"
        >
          {generating ? (
            <>
              <Loader2 className="h-4 w-4 animate-spin spinner-glow" />
              {generatingWeek
                ? `Generating Week ${generatingWeek}...`
                : "Creating Plan..."}
            </>
          ) : (
            <>
              <Sparkles className="h-4 w-4" />
              {roadmap ? "Recalculate Schedule" : "Generate Roadmap"}
            </>
          )}
        </button>
      </div>

      {error && (
        <div className="rounded-lg bg-destructive/10 p-4 text-sm text-destructive">
          {error}
        </div>
      )}

      {/* Generation progress */}
      {generating && generatingWeek && totalWeeksToGen > 0 && roadmap && (
        <div className="rounded-xl p-4 card-dark">
          <div className="mb-2 flex items-center justify-between text-sm">
            <span className="font-medium flex items-center gap-2">
              <Loader2 className="h-4 w-4 animate-spin text-primary spinner-glow" />
              Generating Week {generatingWeek} of {roadmap.total_weeks}
            </span>
            <span className="text-muted-foreground tabular-nums">
              {Math.round(((generatingWeek - 1) / roadmap.total_weeks) * 100)}%
            </span>
          </div>
          <div className="h-2.5 rounded-full bg-muted">
            <div
              className="h-2.5 rounded-full bg-gradient-to-r from-primary to-amber-600 transition-all duration-500"
              style={{
                width: `${((generatingWeek - 1) / roadmap.total_weeks) * 100}%`,
              }}
            />
          </div>
        </div>
      )}

      {roadmap ? (
        <div className="space-y-4">
          {/* Roadmap Timeline with Vertical Progress Line */}
          <div className="relative">
            {/* Vertical progress line */}
            <div className="absolute left-[19px] top-8 bottom-8 w-[2px] bg-border">
              <div 
                className="w-full bg-primary transition-all duration-500"
                style={{
                  height: `${((roadmap.current_week - 1) / roadmap.content.weeks.length) * 100}%`,
                }}
              />
            </div>

            {/* Week list */}
            <div className="space-y-4">
              {roadmap.content.weeks?.map((week, index) => {
                const isExpanded = expandedWeek === index;
                const isCurrent = index === roadmap.current_week - 1;
                const isPast = index < roadmap.current_week - 1;
                const isPending = week.pending || !week.days?.length;
                const isGeneratingThis = generatingWeek === week.week;
                
                // Calculate progress for current/past weeks
                const weekProgress = isPast ? 100 : isCurrent ? 46 : 0;

                return (
                  <div
                    key={index}
                    className={`relative rounded-2xl border transition ${
                      isCurrent
                        ? "border-primary/50 bg-gradient-to-br from-primary/10 to-transparent"
                        : isPast
                        ? "border-primary/30 bg-primary/5"
                        : isPending
                        ? "border-border/30 bg-card/50 opacity-75"
                        : "border-border/50 bg-card"
                    }`}
                  >
                    <button
                      onClick={() => !isPending && setExpandedWeek(isExpanded ? null : index)}
                      disabled={isPending}
                      className="flex w-full items-start gap-4 p-5 text-left disabled:cursor-default"
                    >
                      {/* Week number badge with checkmark for completed */}
                      <div className="relative flex-shrink-0">
                        <div
                          className={`flex h-10 w-10 items-center justify-center rounded-full text-sm font-bold transition ${
                            isPast
                              ? "bg-primary text-primary-foreground"
                              : isCurrent
                              ? "bg-primary text-primary-foreground ring-4 ring-primary/20"
                              : isPending
                              ? "bg-muted/50 text-muted-foreground"
                              : "bg-muted text-muted-foreground"
                          }`}
                        >
                          {isGeneratingThis ? (
                            <Loader2 className="h-5 w-5 animate-spin" />
                          ) : isPast ? (
                            <CheckCircle2 className="h-5 w-5" />
                          ) : (
                            index + 1
                          )}
                        </div>
                      </div>

                      <div className="flex-1 min-w-0">
                        <div className="flex items-start justify-between gap-3">
                          <div className="flex-1 min-w-0">
                            <div className="flex items-center gap-2">
                              <span className="text-xs font-semibold text-muted-foreground uppercase tracking-wide">
                                Weeks {week.week || index + 1}
                              </span>
                              {isCurrent && (
                                <span className="rounded-full bg-primary px-2 py-0.5 text-[10px] font-bold text-primary-foreground">
                                  CURRENT
                                </span>
                              )}
                            </div>
                            <p className="mt-1 font-semibold text-base sm:text-lg">
                              {week.title}
                            </p>
                            {week.description && (
                              <p className="mt-1 text-sm text-muted-foreground">
                                {week.description}
                              </p>
                            )}
                            {isPending && !isGeneratingThis && (
                              <p className="mt-1 text-xs text-muted-foreground/60 italic">
                                Waiting to generate...
                              </p>
                            )}
                            {isGeneratingThis && (
                              <p className="mt-1 text-xs text-primary/80 italic">
                                Generating tasks...
                              </p>
                            )}
                          </div>
                          
                          <div className="flex items-center gap-2">
                            {!isPending && (
                              <>
                                {(isCurrent || isPast) && (
                                  <div className="hidden sm:block">
                                    <div className="text-xs text-muted-foreground mb-1">Progress</div>
                                    <div className="flex items-center gap-2">
                                      <div className="h-2 w-24 rounded-full bg-muted">
                                        <div
                                          className="h-2 rounded-full bg-primary transition-all"
                                          style={{ width: `${weekProgress}%` }}
                                        />
                                      </div>
                                      <span className="text-xs font-semibold tabular-nums">{weekProgress}%</span>
                                    </div>
                                  </div>
                                )}
                                {isExpanded ? (
                                  <ChevronDown className="h-5 w-5 text-muted-foreground" />
                                ) : (
                                  <ChevronRight className="h-5 w-5 text-muted-foreground" />
                                )}
                              </>
                            )}
                          </div>
                        </div>
                      </div>
                    </button>

                    {isExpanded && !isPending && week.days && (
                      <div className="border-t border-border/30 px-5 pb-5">
                        <div className="pt-4 space-y-5">
                          <h4 className="text-sm font-semibold text-muted-foreground uppercase tracking-wide">Modules</h4>
                          {week.days.map((day, dayIndex) => {
                            const dayCompleted = dayIndex === 0; // Mock: first day completed
                            const dayInProgress = dayIndex === 1; // Mock: second day in progress
                            
                            return (
                              <div key={dayIndex} className="space-y-3">
                                <div className="flex items-center gap-3">
                                  <div
                                    className={`flex h-6 w-6 items-center justify-center rounded-full text-xs font-bold ${
                                      dayCompleted
                                        ? "bg-primary text-primary-foreground"
                                        : dayInProgress
                                        ? "border-2 border-primary bg-transparent text-primary"
                                        : "bg-muted text-muted-foreground"
                                    }`}
                                  >
                                    {dayCompleted ? (
                                      <CheckCircle2 className="h-4 w-4" />
                                    ) : (
                                      dayIndex + 1
                                    )}
                                  </div>
                                  <div className="flex-1">
                                    <p className="text-sm font-semibold">
                                      {day.title || `Day ${day.day || dayIndex + 1}`}
                                    </p>
                                  </div>
                                  <div className="flex items-center gap-2">
                                    <button className="rounded-md border border-border px-3 py-1 text-xs font-medium hover:bg-muted/50 transition">
                                      {dayCompleted ? "Review" : dayInProgress ? "Start" : "Theory"}
                                    </button>
                                    {dayInProgress && (
                                      <button className="rounded-md bg-primary px-3 py-1 text-xs font-semibold text-primary-foreground hover:bg-primary/90 transition">
                                        Start 📚
                                      </button>
                                    )}
                                  </div>
                                </div>
                                
                                {/* Task list for expanded day */}
                                {dayInProgress && day.tasks && (
                                  <div className="ml-9 space-y-2 border-l-2 border-border pl-4">
                                    {day.tasks.slice(0, 3).map((task, ti) => (
                                      <div
                                        key={task.id || ti}
                                        className="flex items-start gap-2 text-sm"
                                      >
                                        <div className="mt-1 text-muted-foreground">
                                          {TYPE_ICONS[task.type] || <BookOpen className="h-3.5 w-3.5" />}
                                        </div>
                                        <div className="flex-1">
                                          <p className="font-medium">{task.title}</p>
                                          {task.description && (
                                            <p className="text-xs text-muted-foreground mt-0.5">
                                              {task.description}
                                            </p>
                                          )}
                                        </div>
                                        {task.duration_minutes && (
                                          <span className="text-xs text-muted-foreground whitespace-nowrap">
                                            {task.duration_minutes}m
                                          </span>
                                        )}
                                      </div>
                                    ))}
                                  </div>
                                )}
                              </div>
                            );
                          })}
                        </div>
                      </div>
                    )}
                  </div>
                );
              })}
            </div>
          </div>
        </div>
      ) : (
        <div className="flex flex-col items-center justify-center rounded-2xl border border-dashed border-border py-16 text-center card-dark">
          <Map className="mb-4 h-12 w-12 text-muted-foreground" />
          <h2 className="mb-2 text-xl font-semibold">No Roadmap Yet</h2>
          <p className="mb-6 max-w-md text-sm text-muted-foreground">
            Click &quot;Generate Roadmap&quot; to create a personalized learning path
            based on your profile, target role, and skill level.
          </p>
        </div>
      )}
    </div>
  );
}
